### PR TITLE
Landing page

### PR DESCRIPTION
**Pull request by GonSanchezS**
This pull request creates a landing page in the application index.

### CODE REVIEW

**Comment by kellylougheed** [comment]
Pulled this onto my computer, and it looks great! My only suggestion that we make a more obvious link to access the list of games -- it took me a little bit to figure out that I had to click on my email address. Maybe that could be an option beside "Play your first game." I don't think the user has to be authenticated before viewing the available games (though you could certainly change that if you wanted). Anyway, it looks good and I'll be happy to approve it soon!

**Comment by GonSanchezS** [comment]
@kellylougheed thanks! It's still a work in progress, so feel free to pull every now and then to checkout how it looks. I'm working on the landing page right now, and will move onto how the actual app looks when logged in, later this week.

This is how it looks, as of right now:

captura de pantalla 2016-12-20 a las 5 52 06 pm

I agree with your suggestion re: making games easier to find!

**Comment by PamBWillenz** [comment]
Looks good Gonzalo - Are you going to add an image/icon to the page? I liked Matt's 
up_all_knight_360

**Comment by GonSanchezS** [comment]
@PamBWillenz as mentioned, it's a work in progress. Where do you suggest we add that picture? Also, I will definitely add those circles.

**Comment by PamBWillenz** [comment]
@GonSanchezS either below the "Up All Knight" - could right justify text or put on right.

**Comment by GonSanchezS** [comment]
I finished styling all sections. @PamBWillenz personally, I like more the text-only logo, but I'd be happy to adjust if the team prefers. That said, if we want to make the change, we probably need a less-detailed image for the logo.

**Pull request merged**
