### PR TITLE
fix pawn color positions, refactor moving backwards, add game.is_piec…

### PR DESCRIPTION
**Pull request by PamBWillenz**
…e_present? on 1 & 2 square methods. Found pawn moving errantly on the board - sometimes able to capture, sometimes not and not able to move 2 squares for first move. Using byebug line by line, found error in color layout for board (had white on 1 and black on 6, needed to be reversed). Also found an issue with the piece model with range - min-max = nil. This seemed to mess with the diagonal moves. Kelly is working on this.

All tests are passing and pawn moves like a champ locally.

### CODE REVIEW

**Comment by kellylougheed** [comment]
What's the issue with range? @FsDevNinja actually fixed the problem I brought up today (I thought he was telling me about the problem, but he was telling me that he had fixed it, haha). Not sure if his solution has been merged yet, though.

**Comment by PamBWillenz** [comment]
cool, Kelly @kellylougheed - when we were going through the code line-by-line with byebug to see why the pawn and then the queen were not able to move diagonally, we found that when the range min = max, it resulted in nil and skipped the rest of the code in the method, when it should have returned a position. The pawn also couldn't move 2 spaces from home row. Matt created some logic to make sure min/max wouldn't = nil so the code would run beneath it. After that fix, we checked all the active pieces on the board to make sure they could do their moves and not go out of their parameters. Does that make sense?

**Comment by kellylougheed** [comment]
Yes -- so the issue is resolved?

**Comment by PamBWillenz** [comment]
Yes - issue should be resolved shortly.

**Pull request merged**
