### PR TITLE
Add check? method

### PR DESCRIPTION
**Pull request by GonSanchezS**
This pull request adds a valid `check?` method. It:

1. Adds a `check?` method in the `Game` model.
2. Adds passing tests for `check?` for `true` and `false` in both `white_player` and `black_player`.
3. Adds some relationships between models.

### CODE REVIEW

**Comment by kellylougheed** [comment]
Looks great, Gonzalo! It looks like your testing code could be refactored a bit to avoid repetition. Maybe use some let statements in the context block instead of creating the games & pieces individually for every test? Once that happens, I'm happy to approve & merge this. Great work!

**Comment by GonSanchezS** [comment]
@kellylougheed the tower position is still unique for each test. How would you approach that?

**Comment by kellylougheed** [comment]
You could make the tower position unique for each test, but for the other variables that are the same, you could just make them let statements in the context block so you don't have to repeat it

**Comment by PamBWillenz** [comment]
Looks good, Gonzalo. I can approve (and merge) after you finish making any more test changes plus fixing your conflicting files.

**Pull request merged**
