### PR TITLE
made opposite_piece_present? helper method

### PR DESCRIPTION
**Pull request by FsDevNinja**
So what was happening was  that the is_obstructed method was returning true if there was a piece in the destination coordinates even if the opposite color. adding the opposite_piece_present? was just one of the ways i could see fixing this problem. I went with this approach instead of dealing with the range array way.

### CODE REVIEW

**Comment by kellylougheed** [comment]
Yeah, the purpose of is_obstructed? was to check all the squares in between the location & destination (sorry if that wasn't clear). I like the helper method. Should we add some tests for it? Other than that, happy to approve this!

**Comment by FsDevNinja** [comment]
Yes... so when i was moving a pawn from 1,1 to 2,2 the range was coming back as 2..2. in one of the pawn tests, i need a piece to be diagonal from pawn and if there is a piece of opposite color then they could move and capture...so with the range being 2..2 it was saying it was obstructed before it looked at what color it was...yeah.. i'll add a test for it.

**Comment by kellylougheed** [comment]
I made some fixes on is_obstructed? in my queen pull request that would make that range now return nil, I think. You looked at that fix, right? I really want that to be merged in ASAP so I can make sure it's compatible with what everyone else is doing! Anyway, feel free to experiment with that fix I made.

**Comment by FsDevNinja** [comment]
oh.. no.. .i just say the other PR of adding the helper methods... okay.. then yeah we need that merged too...

**Pull request closed without merging**
