### PR TITLE
Add style to the game section of the app

### PR DESCRIPTION
**Pull request by GonSanchezS**
This pull request will style the game section of the app. This includes: 

- The game list / user dashboard.
- Creating a new game.
- The actual game view {in progress}.
- The sign up screen
- The sign in screen
- Add an `/about` page that will need more content.

### CODE REVIEW

**Review by PamBWillenz — COMMENTED** [review]
Nice work, @GonSanchezS. What about links to the icons in the footer? I can help with that if you want. I'll approve after that, if you want to add to this PR or me or you create a new one.
[Looking at the app, I guess the icons are just there to show what tools we used - maybe links aren't necessary].

**Review by PamBWillenz — APPROVED** [review]

**Comment by GonSanchezS** [comment]
@PamBWillenz let's merge this, and create a new PR. I'm taking a few days off, but I'll be back Monday and I'll keep working on this!

**Comment by PamBWillenz** [comment]
@GonSanchezS sounds good. Need another thumbs up and also need to fix conflicts in branch.

**Comment by kellylougheed** [comment]
@GonSanchezS I love your work! The only problem is that on the new game page and on the ranking page, some of the fonts are the same dark-blue color as the background, and I can't read them. Also, I would love it if someone could double-check my conflict resolution on show.html.erb!

**Pull request merged**
